version: '3.8'

services:

    database:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=hymns_Root_Pass
            - MYSQL_DATABASE=hymns_db
            - MYSQL_USER=hymns_user
            - MYSQL_PASSWORD=hymns_Pass

    redis:
        image: redis:5-alpine
        ports:
            - "6379:6379"

    hymnslocal-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        container_name: hymnslocal-elasticsearch
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        restart: always
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - ELASTIC_PASSWORD=hymns_elastic_Pass
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - es-net

    kibana:
        depends_on:
            - hymnslocal-elasticsearch
        image: docker.elastic.co/kibana/kibana:8.6.2
        volumes:
            - kibana-data:/usr/share/kibana/data
        ports:
            - "5601:5601"
        restart: always
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=http://hymnslocal-elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=hymns_elastic_Pass
        networks:
            - es-net

    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net
        environment:
            - RABBITMQ_DEFAULT_USER=hymns_rabbitmq_user
            - RABBITMQ_DEFAULT_PASS=hymns_rabbitmq_Pass

networks:
    rabbitmq_go_net:
        driver: bridge
    es-net:
        driver: bridge

volumes:
    elasticsearch-data:
        driver: local
    kibana-data:
        driver: local