version: '3'

services:

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: hymns_Root_Pass
      MYSQL_DATABASE: hymns_db
      MYSQL_USER: hymns_user
      MYSQL_PASSWORD: hymns_Pass

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [ "5672", "15672" ]